import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Inventory Management System",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
