import Navbar from "@/components/organisms/nav-bar";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Inventory Management System",
    description: "Generated by create next app",
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <div
            className={`antialiased`}
        >
            <Navbar />
            {children}
        </div>

    );
}
